"""Initial migration: create User and History tables

Revision ID: 47fca1b6a32f
Revises: 
Create Date: 2025-03-12 12:46:26.158251

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '47fca1b6a32f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('operation', sa.String(length=20), nullable=False),
    sa.Column('field_degree', sa.Integer(), nullable=False),
    sa.Column('poly_degree', sa.Integer(), nullable=False),
    sa.Column('coefficient_format', sa.String(length=20), nullable=False),
    sa.Column('output_format', sa.String(length=20), nullable=False),
    sa.Column('coefficients_A', sa.String(length=255), nullable=False),
    sa.Column('coefficients_B', sa.String(length=255), nullable=True),
    sa.Column('result', sa.String(length=255), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('history')
    op.drop_table('user')
    # ### end Alembic commands ###
